version: "3.7"
services:
  app:
    image: "kapral/tg-social-credit-bot:stable"
    depends_on:
      - db
    env_file: .env

  periodic:
    image: "kapral/tg-social-credit-bot:stable"
    depends_on:
      - db
    env_file: .env
    entrypoint: "yacron -c crontab.yaml"

  db:
    image: "mongo:4"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: