version: "3.7"
services:
  app:
    image: "kapral/tg-social-credit-bot:latest"
    depends_on:
      - db
    env_file: .env

  db:
    image: "mongo:4"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: